### PR TITLE
add gdp drifter traj

### PR DESCRIPTION
**Pull request by philippemiron**

### CODE REVIEW

**Comment by selipot** [comment]
Looks fantastic @philippemiron thank you. Why not plot the sst for the 6h case? The variable is called temp.

**Comment by philippemiron** [comment]
Oh, I did not realize that `sst` was there..

**Comment by philippemiron** [comment]
gdp-hourly

**Comment by selipot** [comment]
This looks really great. I will update the readme in a little bit and merge.

**Comment by selipot** [comment]
Maybe put the two subplots on the same color scale?

**Pull request merged**
